language: go

go:
  - 1.x

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libimage-exiftool-perl
  - env GO111MODULE=on go get -v

script:
- env GO111MODULE=on go test -v ./...